package com.test.PlatformAgonisticTest.data.model;

import java.io.Serializable;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@Document(collection="TestData")
@DynamoDBTable(tableName="TestData")
public class TestData implements Serializable {

	private static final long serialVersionUID = 1409811442961495294L;
	
	@Id
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	protected String id;
	
	@Field
	@DynamoDBAttribute
	protected String strVal;
	
	public TestData() {
		super();
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStrVal() {
		return strVal;
	}

	public void setStrVal(String strVal) {
		this.strVal = strVal;
	}

}